steps:
- id: "CI - Rodando Teste"
  name: 'gcr.io/cloud-builders/go'
  env: ['GOPATH=.']
  args: ['test','gohpa']

- id: "CD - Construindo Imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

- id: "CD - Salvando Imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

- id: "CD - Ajustando os arquivos do k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#samysilveira/go-hpa#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' deployment.yaml > deployment-new.yaml;
      cat ./deployment-new.yaml;

- id: "CD - Atualizando k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - 'f'
    - 'deployment-new.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-gohpa'